name: Build & lint
on: [ push ]

jobs:
  build:
    name: Build & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - shell: bash
        run: npx tsc -b
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_args: "--max-warnings=0 --report-unused-disable-directives"
