name: Build & lint
on: [ push ]

permissions:
  checks: write
  contents: write

jobs:
  build:
    name: Build & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - shell: bash
        run: npx tsc -b
      # Forked: https://github.com/wearerequired/lint-action/issues/788
      - uses: rkuykendall/lint-action@3402def6dea8dbcf0b8ec42431d9345ee3f69c4d
        with:
          eslint: true
          eslint_args: "--max-warnings=0 --report-unused-disable-directives"
